//
//  ListOrderPresenter.swift
//  CleanArchitecture
//
//  Created by Eldon Chan on 3/27/18.
//  Copyright (c) 2018 ByEldon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrderPresentationLogic
{
  func presentSomething(response: ListOrder.Something.Response)
}

class ListOrderPresenter: ListOrderPresentationLogic
{
  weak var viewController: ListOrderDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListOrder.Something.Response)
  {
    let viewModel = ListOrder.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
